Map and Info scroll separate
trynmaps/metrics-mvp pull request #447
Opened 2019-11-22 00:04 UTC by SeannyPhoenix

Fixes #394.
Fixes #406.
On each of these screens, I implemented a nested scroll bars, as suggested by @zachzwy (https://github.com/trynmaps/metrics-mvp/issues/406#issuecomment-552127409).

## Screenshot

![image](https://user-images.githubusercontent.com/12836949/69386740-4adfa100-0c78-11ea-9f5a-a1244128329b.png)

![image](https://user-images.githubusercontent.com/12836949/69386728-42876600-0c78-11ea-868f-adfa24d97ccd.png)

2019-11-22 00:12 UTC, exxonvaldez reviewed
Thanks for taking this on, we were just talking about this yesterday about how we'd like our scrolling behaviors to be more sophisticated.

I'm not sure we want nested scrollbars, though?  That always looks a little odd.  Do you know why @zachzwy changed his mind about fixing the map and preferring nested scrollbars?  Is it easy to prototype having the app bar and map locked in place and have the rest of the page scroll below them?

2019-11-23 03:07 UTC, akgupta89 commented
> Thanks for taking this on, we were just talking about this yesterday about how we'd like our scrolling behaviors to be more sophisticated.
> 
> I'm not sure we want nested scrollbars, though? That always looks a little odd. Do you know why @zachzwy changed his mind about fixing the map and preferring nested scrollbars? Is it easy to prototype having the app bar and map locked in place and have the rest of the page scroll below them?

I believe it looks odd currently because we see two scroll bars next to each other, which I'm not sure why is happening as we want to lock the normal scroll bar and make this a full page application. The reason I suggested nested scrollbars is because we want the map, the top bar, and maybe the route selector to be always visible ideally, I'm not sure how this would play out in mobile view however.

2019-11-23 21:18 UTC, zachzwy commented
> Do you know why @zachzwy changed his mind about fixing the map and preferring nested scrollbars? Is it easy to prototype having the app bar and map locked in place and have the rest of the page scroll below them?

In my mind, either "having the app bar and map locked in place and have the rest of the page scroll below them" or "having nested scroll bar on the RouteTable component" should achieve a pretty similar effect.

2019-11-24 23:34 UTC, hathix requested changes
Just flagging this as "changes requested" given the feedback received so far.

2019-12-05 03:08 UTC, hathix commented
When I ran the page and nuked the header, the problem (of having the content be like 50px taller than the page) went away. So I think your problem has to do with the fixed header.

2019-12-05 07:58 UTC, exxonvaldez requested changes

2019-12-05 07:58 UTC, exxonvaldez commented on frontend/src/App.css
> +  padding-bottom: 50px;
What is the purpose of the padding-bottom?  I tried removing it, and things seem to make more sense without the extra space.

2019-12-05 07:58 UTC, exxonvaldez commented on frontend/src/screens/Dashboard.jsx
> +        <Grid item xs={12} sm={6} style={{ padding: 12 }} className="grid-info-box">
I noticed that this didn't work well for a narrow window.  Note the xs={12} for the grid items, this means that the two items should be full width (and thus one above the other) for extra small windows (mobile browsers, and narrow desktop windows).  The scrollbar goes offscreen and you can't see all the content... basically doesn't work right for that layout.  It's going to be tricky to solve.  For narrow windows, the map goes to a fixed height, and the info item gets the rest of the window below the map.

2019-12-10 05:16 UTC, zachzwy commented on frontend/src/screens/Dashboard.jsx
> +        <Grid item xs={12} sm={6} style={{ padding: 12 }} className="grid-info-box">
When the window width is between 600px ~ 640px, the map is squished.
<img width="642" alt="Screen Shot 2019-12-09 at 9 12 34 PM" src="https://user-images.githubusercontent.com/22914663/70497710-e53d4280-1ac8-11ea-92f7-009d86d04e14.png">

2019-12-11 08:00 UTC, exxonvaldez commented on frontend/src/screens/Dashboard.jsx
> +        <Grid item xs={12} sm={6} style={{ padding: 12 }} className="grid-info-box">
> When the window width is between 600px ~ 640px, the map is squished.

Yeah, there's some resize logic in MapSpider and MapStops where it jumps down in height from 100% to a fixed height for windows below a certain width.  It doesn't exactly match up with the Material UI breakpoints, but should be easy to fix since you can get the breakpoint values from the MUI theme object.  It's a separate issue.

2020-01-30 02:09 UTC, hathix commented
Seanny, do you need any help finishing up this PR?

2020-01-30 03:31 UTC, SeannyPhoenix commented
I'll work on this in the coming week; if I hit a wall, I'll reach out @hathix.

2020-03-05 03:27 UTC, hathix commented
Just resolved some merge conflicts so it's up to date

2023-09-20 06:46 UTC, closed without merging