fix issue # 643
trynmaps/metrics-mvp pull request #645
Opened 2020-05-09 20:11 UTC by arctdav

Fixes #643

2020-05-09 20:13 UTC, arctdav commented
@EddyIonescu

2020-05-15 01:04 UTC, EddyIonescu reviewed
Thanks for making the PR and sorry for the delay in reviewing it; I'll be sure to be more responsive over the next few days (also since it's a long-weekend) for reviewing your changes. 

So there are two issues:
1. While it downloads the feed, it doesn't find the feed, which was part of the ticket. It's fine if you want to leave it as a TODO for another PR. For example, in backend/agencies you'd add a "transitfeed_url" to the yaml file of each agency, then you'd make an API call to that URL as to get the feed versions.
2. The goal isn't to always get the latest version but to get the latest version as of a given date. For example, if the date given is 2020-04-01 and there are GTFS feeds from 2020-05-01, 2020-03-01, and 2020-01-01, we'd want the one from 2020-03-01. Same as above, it's fine if you want to leave it as a TODO for another PR.
From the issue description, the start function should take in two arguments: an agency ID (name of the agency that corresponds to the yaml files in backend/agencies, like ttc or muni).

2020-05-16 23:52 UTC, arctdav commented on backend/download_transitfeed_gtfs.py
> +    :return: True if file was uploaded, else False
@EddyIonescu could you set this as another PR?

2020-05-17 00:02 UTC, arctdav commented
@EddyIonescu, could you make point #1 and #2 in your comment as another PR? I will get back to it when I have time if no one else is interested.

2020-05-18 03:56 UTC, EddyIonescu commented on backend/download_transitfeed_gtfs.py
> +    :return: True if file was uploaded, else False
Clarifying this @arctdav, the try/except wouldn't be needed either (see original comment). Also don't worry about resolving conversations as GitHub automatically buries them when you update your PR; the issue is that resolving conversations makes it hard to see past comments.

2020-05-18 03:59 UTC, EddyIonescu commented on backend/download_transitfeed_gtfs.py
> +    p.unlink()
Why was this resolved?

2020-05-18 04:00 UTC, EddyIonescu commented
@arctdav the issue with not doing #1 and #2 is that then there's nothing to really use the script for. If another contributor picks up the ticket up they can start off from your branch.

2020-05-28 01:06 UTC, hathix requested changes
Please make changes based on Eddy's feedback.

2021-08-08 02:32 UTC, closed without merging